# Getting and Cleaning Data Course Project
## Code Book

January 2015

### Description
This code book contains information regarding the variables in the tidy dataset
and the transformations used to create them.
  
### Original Data
The original dataset for this assignment is 
[here](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip).
A despricption of this data is available at the 
[UCI Machine Learning Repository](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones).

### Data Set Information from UCI MAchine Learning Repository
The experiments have been carried out with a group of 30 volunteers within an age 
bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS,
WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) 
on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear
acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have
been video-recorded to label the data manually. The obtained dataset has been randomly
partitioned into two sets, where 70% of the volunteers was selected for generating the
training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise
filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128
readings/window). The sensor acceleration signal, which has gravitational and body motion
components, was separated using a Butterworth low-pass filter into body acceleration and
gravity. The gravitational force is assumed to have only low frequency components, therefore
a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was
obtained by calculating variables from the time and frequency domain. 

### Attribute Information from UCI Machine Learning Repository
For each record in the dataset it is provided:   
- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.   
- Triaxial Angular velocity from the gyroscope.   
- A 561-feature vector with time and frequency domain variables.   
- Its activity label.   
- An identifier of the subject who carried out the experiment.  

### Brief Over View of Code in run_analysis.R
##### 1. Merges the training and the test sets to create one data set
- Read in the data files  
- Add column names  
- Merge the x, y, and subject datasets for both the test and training data  
- Meger the test and training datasets  

##### 2. Extracts only the measurements on the mean and standard deviation for each measurement. 
- Creates a logical vector to distinguish which fields are desired  
        - mean fields  
        - standard deviation fields  
- Pulls data only in fields where the logical vector indciates **TRUE**  

##### 3. Uses descriptive activity names to name the activities in the data set
- Adds activity names by merging the dataset with the activity_labels dataset  

##### 4. Appropriately labels the data set with descriptive variable names. 
- Clean up the column names where necessary  

##### 5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
- Create a summary dataset with only the mean value of each variable by activity and subject  
- Add activity names to the new "tidy" dataset
- Export the tidy dataset