# Getting and Cleaning Data Course Project
## Read Me File

January 2015

### Overview
The purpose of this project is to demonstrate your ability to collect, work with, and 
clean a data set. The goal is to prepare tidy data that can be used for later analysis. 
You will be graded by your peers on a series of yes/no questions related to the project. 
You will be required to submit: 1) a tidy data set as described below, 2) a link to a 
Github repository with your script for performing the analysis, and 3) a code book that
describes the variables, the data, and any transformations or work that you performed to
clean up the data called CodeBook.md. You should also include a README.md in the repo 
with your scripts. This repo explains how all of the scripts work and how they are 
connected.  

### Data
The original dataset for this assignment is 
[here](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip).
A despricption of this data is available at the 
[UCI Machine Learning Repository](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones).  

### Script Modifications
To run the script in run_analysis.R, simply change the working directory to where the 
unzipped data files are stored. This is located in line 13 of the code.

### Variables
See the CodeBook file for additional information regarding the variables involved in
this project.